### PR TITLE
Update deps and travis procedures

### PR DESCRIPTION
**Pull request by cbenz**

### CODE REVIEW

**Comment by fpagnoux** [comment]
This broke my installation procedure, due to version conflicts between `api` and `parsers` about the `core` dependency.
I guess what we should learn from this is that a major release of `core` must always be followed by a major release of `parsers`, which I didn't know nor do in the past.

**Comment by cbenz** [comment]
So you think that doing a major release of `parsers` first, could avoid this version mismatch about the `core`?

Could it be related to this issue? https://github.com/pypa/pip/issues/988 (sorry this is quite long...)

**Comment by fpagnoux** [comment]
Not sure it's related, as we had here a clear explicit version conflict, it's not just about the order of dependency loading.

To quote @MattiSG, here is I think the reasoning to adopt (pardon my French):

> 1. `parsers` fait de l’introspection sur `core` ; donc, le contenu de `core` fait partie de son API publique (en entrée).
> 2. la modification de `parsers` l’a rendue incompatible avec `core@2`.
>    => alors on a bien modifié l’API publique de `parsers` d’une manière non rétro-compatible, et il fallait publier une nouvelle version majeure.

**Comment by cbenz** [comment]
Note that I didn't change any calls to Core from Parsers! I bumped the Core dependency version in `setup.py` _just_ for Parsers to be installable. Otherwise since Core was 3.0 we could no more have: `Core == 3.0.0`, Web-Api requiring `Core >= 3.0.0, < 4.0` and Parsers requiring `Core >= 2.0.0, < 3.0`.

That's not solvable! So I bumped Parsers dependency over Core to solve the constraints.

Should I have changed Parsers requiring `Core >= 2.0.0, < 4.0` to be more flexible?

**Comment by MattiSG** [comment]
> Should I have changed Parsers requiring Core >= 2.0.0, < 4.0 to be more flexible?

If you were compatible with them, yes, of course. Constraints are there to avoid breaks, not to create them  :wink:

**Comment by cbenz** [comment]
@fpagnoux Would you prefer to relax the constraint as just said on my previous message, or stay like that and do better next time?

**Comment by fpagnoux** [comment]
No need to change it now, let's try to be more careful in the future :)

**Pull request merged**
